name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- checkout source ---
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src

      # --- checkout builds branch ---
      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: builds
          fetch-depth: 0
          path: builds

      # --- clean old outputs ---
      - name: Clean old builds
        run: |
          rm -f $GITHUB_WORKSPACE/builds/*.cs3
          rm -f $GITHUB_WORKSPACE/builds/plugins.json

      # --- setup java ---
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # --- setup android ---
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # --- build plugins ---
      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      # --- push results ---
      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Build from $GITHUB_SHA" || exit 0
          git push --force origin builds
